### ISSUE TITLE
User should be able to buy/sell in reserve with/to any token

### ISSUE THREAD

**Issue by tomerGD** [GoodDollar/GoodProtocol#10]
Buy (input token -> G$)
- [x] if input token is not cDAI or DAI, convert to DAI through DEX (uniswap?) then mint CDAI
- [x] if input token is DAI mint cDAI
- [x] continue with regular buy with cDAI
- [x] optional receiver of GDX (if a contract is buying from reserve in the name of some user, it might want to attribute the GDX to that user)
- [x] add input parameter for DEX min return (slippage, front runner)

Sell (G$ -> target token)
- [x] get cDAI for sold G$s
- [x] if target token is not cDAI or DAI, redeem cDAI to dai, convert DAI to target token on DEX
- [x] if target token is DAI redeem cDAI
- [x] send target token to seller
- [x] add input parameter for DEX min return (slippage, front runner)

Price
- [x] return price in user input token based on uniswap current token->DAI rate , cDAI(currentPrice())->DAI

- modify the Reserve buy/sell methods
- should use a helper contract? so reserve contract doesnt grow in size?

**Comment by sirpy** [comment]
not much. it is just a helper contract
1. currently it charges 0.2% for performing the exchange through it, so decide if we want to remove that and if not what to do with the income
2. do we want to keep it as an upgradable contract? if so we need to transfer ownership to the DAO

**Comment by tomerGD** [comment]
1. let's recmove the fee
2. i think this contracts should be immutable 

See the PRD and add your comments 
https://docs.google.com/document/d/1TAqmKB7E-JHOZcURBedH9NzeH74vO9vsXejLXI7bhgc/edit#

**Comment by sirpy** [comment]
@tomerGD see my updated description and proposed flow. which will be implemeented directly in reserve
