### ISSUE TITLE
Adjust expension rate to become weekly instead of daily. 

### ISSUE THREAD

**Issue by tomerGD** [GoodDollar/GoodProtocol#11]
@sirpy do you need me to pull you out the calculation? or you can simply multiply it by 7?

**Comment by sirpy** [comment]
@tomerGD 
the expansion rate will be based on days passed since last expansions

ratio = ratio * expansionRate^daysPassed

**Comment by tomerGD** [comment]
sweet so we have the agility to easily change it between a week to a month?

**Comment by tomerGD** [comment]
is that done?
