### ISSUE TITLE
Fix totalClaimsPerUser stats

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocol#16]
@IvanRF commented on [Wed Apr 07 2021](https://github.com/GoodDollar/GoodContracts/pull/214)

# Description

I just tried to read the `totalClaimsPerUser` from the contract and it always returned `0`.
Then I found this issue on the contract code.

see PR https://github.com/GoodDollar/GoodContracts/pull/214

**Comment by IvanRF** [comment]
@sirpy will the `UBIScheme` contract be moved to this repo? I could not find it

**Comment by sirpy** [comment]
@aliberkhsl this is fixed in #63 please review
