### ISSUE TITLE
(chore) fundmanager calcsortedcontracts should return more useful results

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocol#168]
currently user has to enter the estimated gas he will spend, this is not intuitive plus the threshold calculation is done
over this max gas the user enters and not on the actual gas that is required
return a list, each row should be:
 - contractAdded
 - interest collected so far including this contract
 - max gas that will pass threshold (depending if it is x4 or without x4)
 - actual required gas to complete interest collect

**Comment by aliberkhsl** [comment]
We have two array so far addresses and balances so if I would just return this two array we can calculate interest collected so far including this contract @sirpy
