### ISSUE TITLE
votingPeriodBlocks number on Fuse network

### ISSUE THREAD

**Issue by IvanRF** [GoodDollar/GoodProtocol#17]
https://github.com/GoodDollar/GoodProtocol/blob/df2b192d5ea81d1f0ca3a353d72be9d20572dac0/contracts/governance/CompoundVotingMachine.sol#L43

I think that Fuse network has a new block every 5 seconds.

**Comment by sirpy** [comment]
yes it.
the votinPeriodBlocks is an input in the constructor
when deployed on fuse it will be 5760*3 and on ethereum 5760
