### ISSUE TITLE
add swaphelper test and improve tests

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocol#173]
- [x] test swap helper library
- [x] add generic DRY test for aave and compound to verify maxsafeamount and direct and hop swaps work
  - token swap (compound  and aave)
  - comp hardcoded swap via eth(compound)
- [x] DRY staking tests for different decimals tokens
  - generic tests per decimals
  - succint tests - do we need all these test cases? think what is specifically relevant for  decimals and is already test in  stakingrewards and might be redundant.
  -  verify tests are actually testing what they are supposed to test, dryer code, less recuring expects across tests more focused expects at the end of the test
     - [x] for example: calcsorted tests not checking correctly

**Comment by aliberkhsl** [comment]
1. stake should generate some interest and should be used to generate UBI
This test is required to check for if it collects interests for different decimals token without problem
2.it should get rewards with updated values
This test is required to check for if it calculates rewards amounts according to different decimals tokens properly
3.should be able earn to 50% of rewards when owns 50% of total productivity
This test is to check if it calculates fractions of pool properly for different decimal token staking contracts so see if calculations are generic
4.Accumulated per share has enough precision when reward << totalproductivity
This test is to check if it calculates accumulated per share in the edge case properly
