### ISSUE TITLE
release tasks

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocol#177]
- [x] snapshot
   - [x] explanation
   - [x] helper code to claim gdx/rep
   - [x] update code to collect until snapshot block
   - [x] etoro staking 1M?
- [x] decide on ubi initial cycle
- [x] fill first 90 days of ubi
- [x] donation of interest?
- [x] staking 1M
- [x] bridge ownership
- [x] bridge limites

**Comment by tomerGD** [comment]
how much did we say we need for the first week of UBI?

**Comment by tomerGD** [comment]
bridge ownership should be by the dao

**Comment by tomerGD** [comment]
bridge limits 

Daily limit 
200M G$ 

Single transfer max 30M 

Minimum is determined by fuse

**Comment by tomerGD** [comment]
1M is scheduled for first of September
