### ISSUE TITLE
Buy/Sell guide

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocol#181]
- [x] guide on gitbook
- [x] include images from etherscan
- [ ] cover different cases (dai/cdai/multihop)

**Comment by tomerGD** [comment]
https://docs.google.com/document/d/17QkZbozhOgO6jANMMHsWAx0xmtXsvFkeKg6RCZewwRM/edit

**Comment by tomerGD** [comment]
existing guide attached above
