### ISSUE TITLE
Protocol Dashboard

### ISSUE THREAD

**Issue by tomerGD** [GoodDollar/GoodProtocol#2]
All tickets under this epic should be built as a private dashboard for GoodDollar team.

Add the following data in the doc both to the graph
https://docs.google.com/document/d/1Jg57Hk8J3DoRqmmNropWe7vP-26u7Qa6xlVjwITm1tI/edit#

add the names of the tags to the following google sheet: 
https://docs.google.com/spreadsheets/d/1Ka9O4Lm3w9N9lYN4mRFYVRvvGCHZHqGgn-2ZK_2YZYE/edit#gid=0

**Comment by sirpy** [comment]
@tomerGD we need to split it into smaller issues and align them with UI needs timeline
what is the justification for each data we collect, when do we need each data and why

**Comment by tomerGD** [comment]
@sirpy  ok turning that into an epic, and splitting into little tickets with priorities
