### ISSUE TITLE
Create plugin for defilama

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocol#206]
https://docs.llama.fi/list-your-project/submit-a-project

## TVL
Reading their docs I think our TVL calculation should currently be:

mainnet:
- cUSDC balance of our aave staking contract (V2)
- cDAI staked in our compound staking contract (v1+v2)
- cDAI balance of reserve

fuse:
- G$ balance of our governance staking contract 
- fuse staked in fuse's consensus contract by our FuseStaking contract

**Comment by Shloyem** [comment]
Hey @sepu85 can you please review and close/approve it? 
The listing: https://defillama.com/protocol/gooddollar

Methodology was:

**TVL:**
	_Mainnet:_
		cUSDC balance of our [aave staking contract (V2)](https://etherscan.io/address/0xF4c34BED7Dd779485692bB1857aCf9c561B45010)
		cDAI staked in our compound staking contract [v1](https://etherscan.io/address/0xD33bA17C8A644C585089145e86E282fada6F3bfd) + [v2](https://etherscan.io/address/0x02416eb83CFf1f19163F21010149C3867f3261e1)
		cDAI balance of [reserve](https://etherscan.io/address/0x6C35677206ae7FF1bf753877649cF57cC30D1c42)
	 _Fuse:_
		NOT COUNTED BECAUSE [THEY DONT COUNT PoS UNTIL TOKENIZED](https://github.com/DefiLlama/DefiLlama-Adapters/pull/1652)- (fuse staked in fuse's consensus contract by our FuseStaking contract)
**Staking:**
	_Fuse:_
		G$ balance of our [governance staking contract](0xFAF457Fb4A978Be059506F6CD41f9B30fCa753b0)
**Treasury:**
	_Fuse:_
		G$ balance of our [community safe](https://explorer.fuse.io/address/0x5Eb5f5fE13d1D5e6440DbD5913412299Bc5B5564/tokens)
		G$ balance of our [FuseStaking contract](https://explorer.fuse.io/address/0xA199F0C353E25AdF022378B0c208D600f39a6505/tokens)

G$ were converted to USD based on current price at the reserve(through conversion to DAI) because they usually pull the price from CoinGecko

**Comment by sepu85** [comment]
he @Shloyem I'm re-opening this issue as we need to update the new contracts after we deployed the fix.

DeFiLlama is not showing the right metrics.

![Captura de pantalla 2022-03-14 a las 13.04.39.png](https://images.zenhubusercontent.com/5c17881eb59cfb36f158d73a/4d52fde7-3a3d-4834-a735-bfe2c78bf948)

**Comment by Shloyem** [comment]
Hey @sepu85 thanks for bringing it up on the weekly PPP.
Just sent them [this PR fix](https://github.com/DefiLlama/DefiLlama-Adapters/pull/1918/files) according to [item 233 Adjust Defi-Llama plugin for new contracts](https://app.zenhub.com/workspaces/goodprotocol-6051b4b7bece6d001114bf5f/issues/gooddollar/goodprotocol/233).
