### ISSUE TITLE
Reduce size of GoodReserveCDai contract

### ISSUE THREAD

**Issue by aliberkhsl** [GoodDollar/GoodProtocol#23]
GoodReserveCDai contract size is too big right now, maybe we can reduce it,
Possibilities:

- Maybe we can move GDX to another contract?

- maybe we can use some sort of library or another contract for view functions?

**Comment by sirpy** [comment]
@aliberkhsl i've optimized it a little further
moved DSMath inline
remove the currentPrice(token) method

**Comment by sirpy** [comment]
@aliberkhsl also found out that using internal function instead of modifier also reduces size
