### ISSUE TITLE
should have generic staking contract

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocol#27]
- [x] copy from branch https://github.com/GoodDollar/GoodContracts/tree/193-Integrating-library-with-staking-contract/stakingModel/contracts
the staking contracts AbstractGoodStaking,SimpleStaking,GoodCompoundStaking and the simplestaking test files
- [x] adapt openzeppelin dependencies, use DAOContract for onlyAvatar + onlyFundmanager (maybe refactor to DAOContract to receive nameService also in setDAO?)
- [x] withdraw should accept parameter _amount (how much of stake to withdraw)
- [x] adapt test files to hardhat/waffle

**Comment by aliberkhsl** [comment]
NameService is inheriting from DAOContract
