### ISSUE TITLE
Update FaceID reverification to every 6 months

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodProtocol#273]
## Business Description
To ensure security, FaceID expiry will be updated to 6 months, and all FV wallets asked to renew their FaceID every 6 months. This applies retroactively to existing Face Verified wallets and any new Face Verified wallets. 

## Technical Implementation
*_Outline the technical approach for building the feature. This section is typically filled out by the development team or can contain suggestions._ 
(dev team: @johnsmith-gooddollar @sirpy @L03TJ3) 
- [ ] (What api's / sdk's could possibly be used)

## Design Reference
N/A

**Comment by decentralauren** [comment]
@sirpy Trying to link this ticket as a dependency but unable: https://github.com/GoodDollar/GoodWeb3-Mono/issues/197

**Comment by sirpy** [comment]
this is a governance decision. no need for a ticket.
