### ISSUE TITLE
G$ price should be available via thegraph

### ISSUE THREAD

**Issue by tomerGD** [GoodDollar/GoodProtocol#3]
collect G$ price in reserve. 

add query language to the following excel

https://docs.google.com/spreadsheets/d/1Ka9O4Lm3w9N9lYN4mRFYVRvvGCHZHqGgn-2ZK_2YZYE/edit#gid=0

**Comment by tomerGD** [comment]
Should appear in GoodDollar private board

**Comment by sirpy** [comment]
@tomerGD please check it, then you can close this issue

**Comment by tomerGD** [comment]
checked, closing issue
