### ISSUE TITLE
G$ marketcap should be available via thegraph

### ISSUE THREAD

**Issue by tomerGD** [GoodDollar/GoodProtocol#4]
Add the following details

1. G$ market cap 
2. value of G$ reserve (cDAI/DAI) 
3. Reserve ratio

add query language to the following excel

https://docs.google.com/spreadsheets/d/1Ka9O4Lm3w9N9lYN4mRFYVRvvGCHZHqGgn-2ZK_2YZYE/edit#gid=0

**Comment by sirpy** [comment]
@tomerGD please test it

**Comment by tomerGD** [comment]
Tested, closing
