### ISSUE TITLE
Governance

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocol#47]
Spec 
https://docs.google.com/document/d/1VTIfKBwjDwLaDlGGDhBVkcatKxoWDSNC4KD33AuhjSc/edit#

- [x] guardian veto
- [x] gdao claiming from distribution
- [ ] gooddollar staking for gdao

**Comment by sirpy** [comment]
@tomerGD put governance specs in this epic description

**Comment by tomerGD** [comment]
@sirpy 
See spec added
