### ISSUE TITLE
Team should have basic statistics dashboard on google studio

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocol#6]
Add the following graphs to a private dashboard
- [x] G$ price
- [x] G$ market cap
- [x] value of G$ reserve (cDAI/DAI)
- [x] Reserve ratio
- [x] Total G$ distributed to date 
- [x] Value in Goodstaking

**Comment by sirpy** [comment]
@tomerGD @drptiago is this in the works? please make sure to update issues on zenhub and move them to correct column

**Comment by tomerGD** [comment]
@drptiago are you following the tickets here?

**Comment by drptiago** [comment]
I will keep updated here. I can't find this one Zenhub @tomerGD

**Comment by sirpy** [comment]
@tomerGD
