### ISSUE TITLE
GDX smart contract

### ISSUE THREAD

**Issue by tomerGD** [GoodDollar/GoodProtocol#9]
Develop the following GDX Smart contract 

https://docs.google.com/document/d/17Z8lp4JgR4LneIudUlsQPCArdsO2M32YzhBMI87aSiY/edit#heading=h.4z2o8a5xdfev

**Comment by tomerGD** [comment]
@sirpy can i QA that?

**Comment by sirpy** [comment]
@tomerGD not at the moment, maybe we can deploy to testnet next week
